// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoczW6a74h_Nzv92dDE7QgS5ukPiE4ew',
    appId: '1:1086108263072:web:3adfe41a79e54b92999fc5',
    messagingSenderId: '1086108263072',
    projectId: 'mobile-application-c7b80',
    authDomain: 'mobile-application-c7b80.firebaseapp.com',
    storageBucket: 'mobile-application-c7b80.firebasestorage.app',
    measurementId: 'G-JTDPL4H8L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxNYP8tnHps3-Jg51PGep8UA2zhXuyMcs',
    appId: '1:1086108263072:android:ad011f0b24c61fd9999fc5',
    messagingSenderId: '1086108263072',
    projectId: 'mobile-application-c7b80',
    storageBucket: 'mobile-application-c7b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoVXER2sDY4shCe-jZc5Y18RT04Bfx3BY',
    appId: '1:1086108263072:ios:3fe2d6b73481f0ea999fc5',
    messagingSenderId: '1086108263072',
    projectId: 'mobile-application-c7b80',
    storageBucket: 'mobile-application-c7b80.firebasestorage.app',
    iosBundleId: 'my.edu.tarc.mobileApplicationAss',
  );

}